adding_data_error = "❌ Произошла ошибка при добавлении данных."
name_so_long_error = "❌ Имя слишком длинное. Введите не более 32 символов."

imposible_to_create_table_error = "❌ Невозможно создать базу."
table_does_not_exist_error  = "❌ Такой Базы не существует."
connections_do_not_exist_error= "❌ У вас нет подключений."
connection_does_not_exist_error = "❌ Такого подключения не существует."

def table_name_not_changed_error(table_name):
    return f"❌ Ошибка при изменении имени Базы «{table_name}»"

table_already_exists_error = '❌ База с таким названием уже существует. Введите заново.'

client_does_not_exists_error = "❌ Такого клиента не существует."

marzban_user_add_error = '❌ Ошибка при создании ключа доступа.'
marzban_link_get_error = "❌ Ошибка при выдаче ключа доступа."
excel_table_can_not_create_error = '❌ Ошибка при скачивании таблицы.'